name: Issue Details
on:
  issues:
    types: [opened, reopened, edited]

permissions:
  contents: read
  issues: write
  models: read

jobs:
  issue-details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: genaiscript/issue-details
        run: npx -y genaiscript@latest run issue-details --pull-comment --out-trace $GITHUB_STEP_SUMMARY   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  