name: PR Reviewer
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write
  models: read

jobs:
  pr-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      # - name: Generate GitHub App Token
      #   id: generate-token
      #   uses: tibdex/github-app-token@v2
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: genaiscript/pr-reviewer
        run: npx -y genaiscript@latest run word-review --vars pull_request=${{ github.event.pull_request.number }} --pull-request-reviews --pull-request-comment --out-trace $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}